package com.pharos.walker.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pharos.walker.beans.BLeDeviceInfoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLE_DEVICE_INFO".
*/
public class BLeDeviceInfoBeanDao extends AbstractDao<BLeDeviceInfoBean, Long> {

    public static final String TABLENAME = "BLE_DEVICE_INFO";

    /**
     * Properties of entity BLeDeviceInfoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CreateDate = new Property(1, long.class, "createDate", false, "CREATE_DATE");
        public final static Property Interval = new Property(2, long.class, "interval", false, "INTERVAL");
        public final static Property Rssi = new Property(3, int.class, "rssi", false, "RSSI");
        public final static Property BatteryVolume = new Property(4, int.class, "batteryVolume", false, "BATTERY_VOLUME");
    }


    public BLeDeviceInfoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BLeDeviceInfoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLE_DEVICE_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CREATE_DATE\" INTEGER NOT NULL ," + // 1: createDate
                "\"INTERVAL\" INTEGER NOT NULL ," + // 2: interval
                "\"RSSI\" INTEGER NOT NULL ," + // 3: rssi
                "\"BATTERY_VOLUME\" INTEGER NOT NULL );"); // 4: batteryVolume
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLE_DEVICE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BLeDeviceInfoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreateDate());
        stmt.bindLong(3, entity.getInterval());
        stmt.bindLong(4, entity.getRssi());
        stmt.bindLong(5, entity.getBatteryVolume());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BLeDeviceInfoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreateDate());
        stmt.bindLong(3, entity.getInterval());
        stmt.bindLong(4, entity.getRssi());
        stmt.bindLong(5, entity.getBatteryVolume());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BLeDeviceInfoBean readEntity(Cursor cursor, int offset) {
        BLeDeviceInfoBean entity = new BLeDeviceInfoBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // createDate
            cursor.getLong(offset + 2), // interval
            cursor.getInt(offset + 3), // rssi
            cursor.getInt(offset + 4) // batteryVolume
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BLeDeviceInfoBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreateDate(cursor.getLong(offset + 1));
        entity.setInterval(cursor.getLong(offset + 2));
        entity.setRssi(cursor.getInt(offset + 3));
        entity.setBatteryVolume(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BLeDeviceInfoBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BLeDeviceInfoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BLeDeviceInfoBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
